[project]
name = "workshop"
version = "0.1.0"
description = "Python Environment Workshop"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "jupyter>=1.1.1",
    "matplotlib>=3.10.8",
    "polars>=1.38.0",
    "scikit-learn>=1.8.0",
]
